name: Angular - Tests
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run-script build  # package.json -> "scripts"
    # - run: npm run-script test
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@master # file: sonar-project.properties
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}